// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TakeHomeAssignmentAPI.Data;

#nullable disable

namespace TakeHomeAssignmentAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250305184017_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TakeHomeAssignmentAPI.Models.Packaging", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dimensions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Packagings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dimensions = "1x1x1 cm",
                            Material = "Material 1",
                            Type = "Bag",
                            Weight = 0.5
                        },
                        new
                        {
                            Id = 2,
                            Dimensions = "2x2x2 cm",
                            Material = "Material 2",
                            Type = "Box",
                            Weight = 1.0
                        },
                        new
                        {
                            Id = 3,
                            Dimensions = "3x3x3 cm",
                            Material = "Material 3",
                            Type = "Bag",
                            Weight = 1.5
                        },
                        new
                        {
                            Id = 4,
                            Dimensions = "4x4x4 cm",
                            Material = "Material 4",
                            Type = "Box",
                            Weight = 2.0
                        },
                        new
                        {
                            Id = 5,
                            Dimensions = "5x5x5 cm",
                            Material = "Material 5",
                            Type = "Bag",
                            Weight = 2.5
                        },
                        new
                        {
                            Id = 6,
                            Dimensions = "6x6x6 cm",
                            Material = "Material 6",
                            Type = "Box",
                            Weight = 3.0
                        },
                        new
                        {
                            Id = 7,
                            Dimensions = "7x7x7 cm",
                            Material = "Material 7",
                            Type = "Bag",
                            Weight = 3.5
                        },
                        new
                        {
                            Id = 8,
                            Dimensions = "8x8x8 cm",
                            Material = "Material 8",
                            Type = "Box",
                            Weight = 4.0
                        },
                        new
                        {
                            Id = 9,
                            Dimensions = "9x9x9 cm",
                            Material = "Material 9",
                            Type = "Bag",
                            Weight = 4.5
                        },
                        new
                        {
                            Id = 10,
                            Dimensions = "10x10x10 cm",
                            Material = "Material 10",
                            Type = "Box",
                            Weight = 5.0
                        },
                        new
                        {
                            Id = 11,
                            Dimensions = "11x11x11 cm",
                            Material = "Material 11",
                            Type = "Bag",
                            Weight = 5.5
                        },
                        new
                        {
                            Id = 12,
                            Dimensions = "12x12x12 cm",
                            Material = "Material 12",
                            Type = "Box",
                            Weight = 6.0
                        },
                        new
                        {
                            Id = 13,
                            Dimensions = "13x13x13 cm",
                            Material = "Material 13",
                            Type = "Bag",
                            Weight = 6.5
                        },
                        new
                        {
                            Id = 14,
                            Dimensions = "14x14x14 cm",
                            Material = "Material 14",
                            Type = "Box",
                            Weight = 7.0
                        },
                        new
                        {
                            Id = 15,
                            Dimensions = "15x15x15 cm",
                            Material = "Material 15",
                            Type = "Bag",
                            Weight = 7.5
                        },
                        new
                        {
                            Id = 16,
                            Dimensions = "16x16x16 cm",
                            Material = "Material 16",
                            Type = "Box",
                            Weight = 8.0
                        },
                        new
                        {
                            Id = 17,
                            Dimensions = "17x17x17 cm",
                            Material = "Material 17",
                            Type = "Bag",
                            Weight = 8.5
                        },
                        new
                        {
                            Id = 18,
                            Dimensions = "18x18x18 cm",
                            Material = "Material 18",
                            Type = "Box",
                            Weight = 9.0
                        },
                        new
                        {
                            Id = 19,
                            Dimensions = "19x19x19 cm",
                            Material = "Material 19",
                            Type = "Bag",
                            Weight = 9.5
                        },
                        new
                        {
                            Id = 20,
                            Dimensions = "20x20x20 cm",
                            Material = "Material 20",
                            Type = "Box",
                            Weight = 10.0
                        },
                        new
                        {
                            Id = 21,
                            Dimensions = "21x21x21 cm",
                            Material = "Material 21",
                            Type = "Bag",
                            Weight = 10.5
                        },
                        new
                        {
                            Id = 22,
                            Dimensions = "22x22x22 cm",
                            Material = "Material 22",
                            Type = "Box",
                            Weight = 11.0
                        },
                        new
                        {
                            Id = 23,
                            Dimensions = "23x23x23 cm",
                            Material = "Material 23",
                            Type = "Bag",
                            Weight = 11.5
                        },
                        new
                        {
                            Id = 24,
                            Dimensions = "24x24x24 cm",
                            Material = "Material 24",
                            Type = "Box",
                            Weight = 12.0
                        },
                        new
                        {
                            Id = 25,
                            Dimensions = "25x25x25 cm",
                            Material = "Material 25",
                            Type = "Bag",
                            Weight = 12.5
                        },
                        new
                        {
                            Id = 26,
                            Dimensions = "26x26x26 cm",
                            Material = "Material 26",
                            Type = "Box",
                            Weight = 13.0
                        },
                        new
                        {
                            Id = 27,
                            Dimensions = "27x27x27 cm",
                            Material = "Material 27",
                            Type = "Bag",
                            Weight = 13.5
                        },
                        new
                        {
                            Id = 28,
                            Dimensions = "28x28x28 cm",
                            Material = "Material 28",
                            Type = "Box",
                            Weight = 14.0
                        },
                        new
                        {
                            Id = 29,
                            Dimensions = "29x29x29 cm",
                            Material = "Material 29",
                            Type = "Bag",
                            Weight = 14.5
                        },
                        new
                        {
                            Id = 30,
                            Dimensions = "30x30x30 cm",
                            Material = "Material 30",
                            Type = "Box",
                            Weight = 15.0
                        },
                        new
                        {
                            Id = 31,
                            Dimensions = "31x31x31 cm",
                            Material = "Material 31",
                            Type = "Bag",
                            Weight = 15.5
                        },
                        new
                        {
                            Id = 32,
                            Dimensions = "32x32x32 cm",
                            Material = "Material 32",
                            Type = "Box",
                            Weight = 16.0
                        },
                        new
                        {
                            Id = 33,
                            Dimensions = "33x33x33 cm",
                            Material = "Material 33",
                            Type = "Bag",
                            Weight = 16.5
                        },
                        new
                        {
                            Id = 34,
                            Dimensions = "34x34x34 cm",
                            Material = "Material 34",
                            Type = "Box",
                            Weight = 17.0
                        },
                        new
                        {
                            Id = 35,
                            Dimensions = "35x35x35 cm",
                            Material = "Material 35",
                            Type = "Bag",
                            Weight = 17.5
                        },
                        new
                        {
                            Id = 36,
                            Dimensions = "36x36x36 cm",
                            Material = "Material 36",
                            Type = "Box",
                            Weight = 18.0
                        },
                        new
                        {
                            Id = 37,
                            Dimensions = "37x37x37 cm",
                            Material = "Material 37",
                            Type = "Bag",
                            Weight = 18.5
                        },
                        new
                        {
                            Id = 38,
                            Dimensions = "38x38x38 cm",
                            Material = "Material 38",
                            Type = "Box",
                            Weight = 19.0
                        },
                        new
                        {
                            Id = 39,
                            Dimensions = "39x39x39 cm",
                            Material = "Material 39",
                            Type = "Bag",
                            Weight = 19.5
                        },
                        new
                        {
                            Id = 40,
                            Dimensions = "40x40x40 cm",
                            Material = "Material 40",
                            Type = "Box",
                            Weight = 20.0
                        },
                        new
                        {
                            Id = 41,
                            Dimensions = "41x41x41 cm",
                            Material = "Material 41",
                            Type = "Bag",
                            Weight = 20.5
                        },
                        new
                        {
                            Id = 42,
                            Dimensions = "42x42x42 cm",
                            Material = "Material 42",
                            Type = "Box",
                            Weight = 21.0
                        },
                        new
                        {
                            Id = 43,
                            Dimensions = "43x43x43 cm",
                            Material = "Material 43",
                            Type = "Bag",
                            Weight = 21.5
                        },
                        new
                        {
                            Id = 44,
                            Dimensions = "44x44x44 cm",
                            Material = "Material 44",
                            Type = "Box",
                            Weight = 22.0
                        },
                        new
                        {
                            Id = 45,
                            Dimensions = "45x45x45 cm",
                            Material = "Material 45",
                            Type = "Bag",
                            Weight = 22.5
                        },
                        new
                        {
                            Id = 46,
                            Dimensions = "46x46x46 cm",
                            Material = "Material 46",
                            Type = "Box",
                            Weight = 23.0
                        },
                        new
                        {
                            Id = 47,
                            Dimensions = "47x47x47 cm",
                            Material = "Material 47",
                            Type = "Bag",
                            Weight = 23.5
                        },
                        new
                        {
                            Id = 48,
                            Dimensions = "48x48x48 cm",
                            Material = "Material 48",
                            Type = "Box",
                            Weight = 24.0
                        },
                        new
                        {
                            Id = 49,
                            Dimensions = "49x49x49 cm",
                            Material = "Material 49",
                            Type = "Bag",
                            Weight = 24.5
                        },
                        new
                        {
                            Id = 50,
                            Dimensions = "50x50x50 cm",
                            Material = "Material 50",
                            Type = "Box",
                            Weight = 25.0
                        },
                        new
                        {
                            Id = 51,
                            Dimensions = "51x51x51 cm",
                            Material = "Material 51",
                            Type = "Bag",
                            Weight = 25.5
                        },
                        new
                        {
                            Id = 52,
                            Dimensions = "52x52x52 cm",
                            Material = "Material 52",
                            Type = "Box",
                            Weight = 26.0
                        },
                        new
                        {
                            Id = 53,
                            Dimensions = "53x53x53 cm",
                            Material = "Material 53",
                            Type = "Bag",
                            Weight = 26.5
                        },
                        new
                        {
                            Id = 54,
                            Dimensions = "54x54x54 cm",
                            Material = "Material 54",
                            Type = "Box",
                            Weight = 27.0
                        },
                        new
                        {
                            Id = 55,
                            Dimensions = "55x55x55 cm",
                            Material = "Material 55",
                            Type = "Bag",
                            Weight = 27.5
                        },
                        new
                        {
                            Id = 56,
                            Dimensions = "56x56x56 cm",
                            Material = "Material 56",
                            Type = "Box",
                            Weight = 28.0
                        },
                        new
                        {
                            Id = 57,
                            Dimensions = "57x57x57 cm",
                            Material = "Material 57",
                            Type = "Bag",
                            Weight = 28.5
                        },
                        new
                        {
                            Id = 58,
                            Dimensions = "58x58x58 cm",
                            Material = "Material 58",
                            Type = "Box",
                            Weight = 29.0
                        },
                        new
                        {
                            Id = 59,
                            Dimensions = "59x59x59 cm",
                            Material = "Material 59",
                            Type = "Bag",
                            Weight = 29.5
                        },
                        new
                        {
                            Id = 60,
                            Dimensions = "60x60x60 cm",
                            Material = "Material 60",
                            Type = "Box",
                            Weight = 30.0
                        },
                        new
                        {
                            Id = 61,
                            Dimensions = "61x61x61 cm",
                            Material = "Material 61",
                            Type = "Bag",
                            Weight = 30.5
                        },
                        new
                        {
                            Id = 62,
                            Dimensions = "62x62x62 cm",
                            Material = "Material 62",
                            Type = "Box",
                            Weight = 31.0
                        },
                        new
                        {
                            Id = 63,
                            Dimensions = "63x63x63 cm",
                            Material = "Material 63",
                            Type = "Bag",
                            Weight = 31.5
                        },
                        new
                        {
                            Id = 64,
                            Dimensions = "64x64x64 cm",
                            Material = "Material 64",
                            Type = "Box",
                            Weight = 32.0
                        },
                        new
                        {
                            Id = 65,
                            Dimensions = "65x65x65 cm",
                            Material = "Material 65",
                            Type = "Bag",
                            Weight = 32.5
                        },
                        new
                        {
                            Id = 66,
                            Dimensions = "66x66x66 cm",
                            Material = "Material 66",
                            Type = "Box",
                            Weight = 33.0
                        },
                        new
                        {
                            Id = 67,
                            Dimensions = "67x67x67 cm",
                            Material = "Material 67",
                            Type = "Bag",
                            Weight = 33.5
                        },
                        new
                        {
                            Id = 68,
                            Dimensions = "68x68x68 cm",
                            Material = "Material 68",
                            Type = "Box",
                            Weight = 34.0
                        },
                        new
                        {
                            Id = 69,
                            Dimensions = "69x69x69 cm",
                            Material = "Material 69",
                            Type = "Bag",
                            Weight = 34.5
                        },
                        new
                        {
                            Id = 70,
                            Dimensions = "70x70x70 cm",
                            Material = "Material 70",
                            Type = "Box",
                            Weight = 35.0
                        },
                        new
                        {
                            Id = 71,
                            Dimensions = "71x71x71 cm",
                            Material = "Material 71",
                            Type = "Bag",
                            Weight = 35.5
                        },
                        new
                        {
                            Id = 72,
                            Dimensions = "72x72x72 cm",
                            Material = "Material 72",
                            Type = "Box",
                            Weight = 36.0
                        },
                        new
                        {
                            Id = 73,
                            Dimensions = "73x73x73 cm",
                            Material = "Material 73",
                            Type = "Bag",
                            Weight = 36.5
                        },
                        new
                        {
                            Id = 74,
                            Dimensions = "74x74x74 cm",
                            Material = "Material 74",
                            Type = "Box",
                            Weight = 37.0
                        },
                        new
                        {
                            Id = 75,
                            Dimensions = "75x75x75 cm",
                            Material = "Material 75",
                            Type = "Bag",
                            Weight = 37.5
                        },
                        new
                        {
                            Id = 76,
                            Dimensions = "76x76x76 cm",
                            Material = "Material 76",
                            Type = "Box",
                            Weight = 38.0
                        },
                        new
                        {
                            Id = 77,
                            Dimensions = "77x77x77 cm",
                            Material = "Material 77",
                            Type = "Bag",
                            Weight = 38.5
                        },
                        new
                        {
                            Id = 78,
                            Dimensions = "78x78x78 cm",
                            Material = "Material 78",
                            Type = "Box",
                            Weight = 39.0
                        },
                        new
                        {
                            Id = 79,
                            Dimensions = "79x79x79 cm",
                            Material = "Material 79",
                            Type = "Bag",
                            Weight = 39.5
                        },
                        new
                        {
                            Id = 80,
                            Dimensions = "80x80x80 cm",
                            Material = "Material 80",
                            Type = "Box",
                            Weight = 40.0
                        },
                        new
                        {
                            Id = 81,
                            Dimensions = "81x81x81 cm",
                            Material = "Material 81",
                            Type = "Bag",
                            Weight = 40.5
                        },
                        new
                        {
                            Id = 82,
                            Dimensions = "82x82x82 cm",
                            Material = "Material 82",
                            Type = "Box",
                            Weight = 41.0
                        },
                        new
                        {
                            Id = 83,
                            Dimensions = "83x83x83 cm",
                            Material = "Material 83",
                            Type = "Bag",
                            Weight = 41.5
                        },
                        new
                        {
                            Id = 84,
                            Dimensions = "84x84x84 cm",
                            Material = "Material 84",
                            Type = "Box",
                            Weight = 42.0
                        },
                        new
                        {
                            Id = 85,
                            Dimensions = "85x85x85 cm",
                            Material = "Material 85",
                            Type = "Bag",
                            Weight = 42.5
                        },
                        new
                        {
                            Id = 86,
                            Dimensions = "86x86x86 cm",
                            Material = "Material 86",
                            Type = "Box",
                            Weight = 43.0
                        },
                        new
                        {
                            Id = 87,
                            Dimensions = "87x87x87 cm",
                            Material = "Material 87",
                            Type = "Bag",
                            Weight = 43.5
                        },
                        new
                        {
                            Id = 88,
                            Dimensions = "88x88x88 cm",
                            Material = "Material 88",
                            Type = "Box",
                            Weight = 44.0
                        },
                        new
                        {
                            Id = 89,
                            Dimensions = "89x89x89 cm",
                            Material = "Material 89",
                            Type = "Bag",
                            Weight = 44.5
                        },
                        new
                        {
                            Id = 90,
                            Dimensions = "90x90x90 cm",
                            Material = "Material 90",
                            Type = "Box",
                            Weight = 45.0
                        },
                        new
                        {
                            Id = 91,
                            Dimensions = "91x91x91 cm",
                            Material = "Material 91",
                            Type = "Bag",
                            Weight = 45.5
                        },
                        new
                        {
                            Id = 92,
                            Dimensions = "92x92x92 cm",
                            Material = "Material 92",
                            Type = "Box",
                            Weight = 46.0
                        },
                        new
                        {
                            Id = 93,
                            Dimensions = "93x93x93 cm",
                            Material = "Material 93",
                            Type = "Bag",
                            Weight = 46.5
                        },
                        new
                        {
                            Id = 94,
                            Dimensions = "94x94x94 cm",
                            Material = "Material 94",
                            Type = "Box",
                            Weight = 47.0
                        },
                        new
                        {
                            Id = 95,
                            Dimensions = "95x95x95 cm",
                            Material = "Material 95",
                            Type = "Bag",
                            Weight = 47.5
                        },
                        new
                        {
                            Id = 96,
                            Dimensions = "96x96x96 cm",
                            Material = "Material 96",
                            Type = "Box",
                            Weight = 48.0
                        },
                        new
                        {
                            Id = 97,
                            Dimensions = "97x97x97 cm",
                            Material = "Material 97",
                            Type = "Bag",
                            Weight = 48.5
                        },
                        new
                        {
                            Id = 98,
                            Dimensions = "98x98x98 cm",
                            Material = "Material 98",
                            Type = "Box",
                            Weight = 49.0
                        },
                        new
                        {
                            Id = 99,
                            Dimensions = "99x99x99 cm",
                            Material = "Material 99",
                            Type = "Bag",
                            Weight = 49.5
                        },
                        new
                        {
                            Id = 100,
                            Dimensions = "100x100x100 cm",
                            Material = "Material 100",
                            Type = "Box",
                            Weight = 50.0
                        });
                });

            modelBuilder.Entity("TakeHomeAssignmentAPI.Models.Packaging_Hierarchy", b =>
                {
                    b.Property<int>("ParentPackagingId")
                        .HasColumnType("int");

                    b.Property<int>("ChildPackagingId")
                        .HasColumnType("int");

                    b.HasKey("ParentPackagingId", "ChildPackagingId");

                    b.HasIndex("ChildPackagingId");

                    b.ToTable("Packaging_Hierarchies");
                });

            modelBuilder.Entity("TakeHomeAssignmentAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PackagingId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PackagingId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Product 1",
                            PackagingId = 2,
                            Price = 10.99m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Product 2",
                            PackagingId = 3,
                            Price = 21.98m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Product 3",
                            PackagingId = 4,
                            Price = 32.97m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Product 4",
                            PackagingId = 5,
                            Price = 43.96m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Product 5",
                            PackagingId = 6,
                            Price = 54.95m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Product 6",
                            PackagingId = 7,
                            Price = 65.94m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Product 7",
                            PackagingId = 8,
                            Price = 76.93m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Product 8",
                            PackagingId = 9,
                            Price = 87.92m
                        },
                        new
                        {
                            Id = 9,
                            Name = "Product 9",
                            PackagingId = 10,
                            Price = 98.91m
                        },
                        new
                        {
                            Id = 10,
                            Name = "Product 10",
                            PackagingId = 11,
                            Price = 109.90m
                        },
                        new
                        {
                            Id = 11,
                            Name = "Product 11",
                            PackagingId = 12,
                            Price = 120.89m
                        },
                        new
                        {
                            Id = 12,
                            Name = "Product 12",
                            PackagingId = 13,
                            Price = 131.88m
                        },
                        new
                        {
                            Id = 13,
                            Name = "Product 13",
                            PackagingId = 14,
                            Price = 142.87m
                        },
                        new
                        {
                            Id = 14,
                            Name = "Product 14",
                            PackagingId = 15,
                            Price = 153.86m
                        },
                        new
                        {
                            Id = 15,
                            Name = "Product 15",
                            PackagingId = 16,
                            Price = 164.85m
                        },
                        new
                        {
                            Id = 16,
                            Name = "Product 16",
                            PackagingId = 17,
                            Price = 175.84m
                        },
                        new
                        {
                            Id = 17,
                            Name = "Product 17",
                            PackagingId = 18,
                            Price = 186.83m
                        },
                        new
                        {
                            Id = 18,
                            Name = "Product 18",
                            PackagingId = 19,
                            Price = 197.82m
                        },
                        new
                        {
                            Id = 19,
                            Name = "Product 19",
                            PackagingId = 20,
                            Price = 208.81m
                        },
                        new
                        {
                            Id = 20,
                            Name = "Product 20",
                            PackagingId = 21,
                            Price = 219.80m
                        },
                        new
                        {
                            Id = 21,
                            Name = "Product 21",
                            PackagingId = 22,
                            Price = 230.79m
                        },
                        new
                        {
                            Id = 22,
                            Name = "Product 22",
                            PackagingId = 23,
                            Price = 241.78m
                        },
                        new
                        {
                            Id = 23,
                            Name = "Product 23",
                            PackagingId = 24,
                            Price = 252.77m
                        },
                        new
                        {
                            Id = 24,
                            Name = "Product 24",
                            PackagingId = 25,
                            Price = 263.76m
                        },
                        new
                        {
                            Id = 25,
                            Name = "Product 25",
                            PackagingId = 26,
                            Price = 274.75m
                        },
                        new
                        {
                            Id = 26,
                            Name = "Product 26",
                            PackagingId = 27,
                            Price = 285.74m
                        },
                        new
                        {
                            Id = 27,
                            Name = "Product 27",
                            PackagingId = 28,
                            Price = 296.73m
                        },
                        new
                        {
                            Id = 28,
                            Name = "Product 28",
                            PackagingId = 29,
                            Price = 307.72m
                        },
                        new
                        {
                            Id = 29,
                            Name = "Product 29",
                            PackagingId = 30,
                            Price = 318.71m
                        },
                        new
                        {
                            Id = 30,
                            Name = "Product 30",
                            PackagingId = 31,
                            Price = 329.70m
                        },
                        new
                        {
                            Id = 31,
                            Name = "Product 31",
                            PackagingId = 32,
                            Price = 340.69m
                        },
                        new
                        {
                            Id = 32,
                            Name = "Product 32",
                            PackagingId = 33,
                            Price = 351.68m
                        },
                        new
                        {
                            Id = 33,
                            Name = "Product 33",
                            PackagingId = 34,
                            Price = 362.67m
                        },
                        new
                        {
                            Id = 34,
                            Name = "Product 34",
                            PackagingId = 35,
                            Price = 373.66m
                        },
                        new
                        {
                            Id = 35,
                            Name = "Product 35",
                            PackagingId = 36,
                            Price = 384.65m
                        },
                        new
                        {
                            Id = 36,
                            Name = "Product 36",
                            PackagingId = 37,
                            Price = 395.64m
                        },
                        new
                        {
                            Id = 37,
                            Name = "Product 37",
                            PackagingId = 38,
                            Price = 406.63m
                        },
                        new
                        {
                            Id = 38,
                            Name = "Product 38",
                            PackagingId = 39,
                            Price = 417.62m
                        },
                        new
                        {
                            Id = 39,
                            Name = "Product 39",
                            PackagingId = 40,
                            Price = 428.61m
                        },
                        new
                        {
                            Id = 40,
                            Name = "Product 40",
                            PackagingId = 41,
                            Price = 439.60m
                        },
                        new
                        {
                            Id = 41,
                            Name = "Product 41",
                            PackagingId = 42,
                            Price = 450.59m
                        },
                        new
                        {
                            Id = 42,
                            Name = "Product 42",
                            PackagingId = 43,
                            Price = 461.58m
                        },
                        new
                        {
                            Id = 43,
                            Name = "Product 43",
                            PackagingId = 44,
                            Price = 472.57m
                        },
                        new
                        {
                            Id = 44,
                            Name = "Product 44",
                            PackagingId = 45,
                            Price = 483.56m
                        },
                        new
                        {
                            Id = 45,
                            Name = "Product 45",
                            PackagingId = 46,
                            Price = 494.55m
                        },
                        new
                        {
                            Id = 46,
                            Name = "Product 46",
                            PackagingId = 47,
                            Price = 505.54m
                        },
                        new
                        {
                            Id = 47,
                            Name = "Product 47",
                            PackagingId = 48,
                            Price = 516.53m
                        },
                        new
                        {
                            Id = 48,
                            Name = "Product 48",
                            PackagingId = 49,
                            Price = 527.52m
                        },
                        new
                        {
                            Id = 49,
                            Name = "Product 49",
                            PackagingId = 50,
                            Price = 538.51m
                        },
                        new
                        {
                            Id = 50,
                            Name = "Product 50",
                            PackagingId = 51,
                            Price = 549.50m
                        },
                        new
                        {
                            Id = 51,
                            Name = "Product 51",
                            PackagingId = 52,
                            Price = 560.49m
                        },
                        new
                        {
                            Id = 52,
                            Name = "Product 52",
                            PackagingId = 53,
                            Price = 571.48m
                        },
                        new
                        {
                            Id = 53,
                            Name = "Product 53",
                            PackagingId = 54,
                            Price = 582.47m
                        },
                        new
                        {
                            Id = 54,
                            Name = "Product 54",
                            PackagingId = 55,
                            Price = 593.46m
                        },
                        new
                        {
                            Id = 55,
                            Name = "Product 55",
                            PackagingId = 56,
                            Price = 604.45m
                        },
                        new
                        {
                            Id = 56,
                            Name = "Product 56",
                            PackagingId = 57,
                            Price = 615.44m
                        },
                        new
                        {
                            Id = 57,
                            Name = "Product 57",
                            PackagingId = 58,
                            Price = 626.43m
                        },
                        new
                        {
                            Id = 58,
                            Name = "Product 58",
                            PackagingId = 59,
                            Price = 637.42m
                        },
                        new
                        {
                            Id = 59,
                            Name = "Product 59",
                            PackagingId = 60,
                            Price = 648.41m
                        },
                        new
                        {
                            Id = 60,
                            Name = "Product 60",
                            PackagingId = 61,
                            Price = 659.40m
                        },
                        new
                        {
                            Id = 61,
                            Name = "Product 61",
                            PackagingId = 62,
                            Price = 670.39m
                        },
                        new
                        {
                            Id = 62,
                            Name = "Product 62",
                            PackagingId = 63,
                            Price = 681.38m
                        },
                        new
                        {
                            Id = 63,
                            Name = "Product 63",
                            PackagingId = 64,
                            Price = 692.37m
                        },
                        new
                        {
                            Id = 64,
                            Name = "Product 64",
                            PackagingId = 65,
                            Price = 703.36m
                        },
                        new
                        {
                            Id = 65,
                            Name = "Product 65",
                            PackagingId = 66,
                            Price = 714.35m
                        },
                        new
                        {
                            Id = 66,
                            Name = "Product 66",
                            PackagingId = 67,
                            Price = 725.34m
                        },
                        new
                        {
                            Id = 67,
                            Name = "Product 67",
                            PackagingId = 68,
                            Price = 736.33m
                        },
                        new
                        {
                            Id = 68,
                            Name = "Product 68",
                            PackagingId = 69,
                            Price = 747.32m
                        },
                        new
                        {
                            Id = 69,
                            Name = "Product 69",
                            PackagingId = 70,
                            Price = 758.31m
                        },
                        new
                        {
                            Id = 70,
                            Name = "Product 70",
                            PackagingId = 71,
                            Price = 769.30m
                        },
                        new
                        {
                            Id = 71,
                            Name = "Product 71",
                            PackagingId = 72,
                            Price = 780.29m
                        },
                        new
                        {
                            Id = 72,
                            Name = "Product 72",
                            PackagingId = 73,
                            Price = 791.28m
                        },
                        new
                        {
                            Id = 73,
                            Name = "Product 73",
                            PackagingId = 74,
                            Price = 802.27m
                        },
                        new
                        {
                            Id = 74,
                            Name = "Product 74",
                            PackagingId = 75,
                            Price = 813.26m
                        },
                        new
                        {
                            Id = 75,
                            Name = "Product 75",
                            PackagingId = 76,
                            Price = 824.25m
                        },
                        new
                        {
                            Id = 76,
                            Name = "Product 76",
                            PackagingId = 77,
                            Price = 835.24m
                        },
                        new
                        {
                            Id = 77,
                            Name = "Product 77",
                            PackagingId = 78,
                            Price = 846.23m
                        },
                        new
                        {
                            Id = 78,
                            Name = "Product 78",
                            PackagingId = 79,
                            Price = 857.22m
                        },
                        new
                        {
                            Id = 79,
                            Name = "Product 79",
                            PackagingId = 80,
                            Price = 868.21m
                        },
                        new
                        {
                            Id = 80,
                            Name = "Product 80",
                            PackagingId = 81,
                            Price = 879.20m
                        },
                        new
                        {
                            Id = 81,
                            Name = "Product 81",
                            PackagingId = 82,
                            Price = 890.19m
                        },
                        new
                        {
                            Id = 82,
                            Name = "Product 82",
                            PackagingId = 83,
                            Price = 901.18m
                        },
                        new
                        {
                            Id = 83,
                            Name = "Product 83",
                            PackagingId = 84,
                            Price = 912.17m
                        },
                        new
                        {
                            Id = 84,
                            Name = "Product 84",
                            PackagingId = 85,
                            Price = 923.16m
                        },
                        new
                        {
                            Id = 85,
                            Name = "Product 85",
                            PackagingId = 86,
                            Price = 934.15m
                        },
                        new
                        {
                            Id = 86,
                            Name = "Product 86",
                            PackagingId = 87,
                            Price = 945.14m
                        },
                        new
                        {
                            Id = 87,
                            Name = "Product 87",
                            PackagingId = 88,
                            Price = 956.13m
                        },
                        new
                        {
                            Id = 88,
                            Name = "Product 88",
                            PackagingId = 89,
                            Price = 967.12m
                        },
                        new
                        {
                            Id = 89,
                            Name = "Product 89",
                            PackagingId = 90,
                            Price = 978.11m
                        },
                        new
                        {
                            Id = 90,
                            Name = "Product 90",
                            PackagingId = 91,
                            Price = 989.10m
                        },
                        new
                        {
                            Id = 91,
                            Name = "Product 91",
                            PackagingId = 92,
                            Price = 1000.09m
                        },
                        new
                        {
                            Id = 92,
                            Name = "Product 92",
                            PackagingId = 93,
                            Price = 1011.08m
                        },
                        new
                        {
                            Id = 93,
                            Name = "Product 93",
                            PackagingId = 94,
                            Price = 1022.07m
                        },
                        new
                        {
                            Id = 94,
                            Name = "Product 94",
                            PackagingId = 95,
                            Price = 1033.06m
                        },
                        new
                        {
                            Id = 95,
                            Name = "Product 95",
                            PackagingId = 96,
                            Price = 1044.05m
                        },
                        new
                        {
                            Id = 96,
                            Name = "Product 96",
                            PackagingId = 97,
                            Price = 1055.04m
                        },
                        new
                        {
                            Id = 97,
                            Name = "Product 97",
                            PackagingId = 98,
                            Price = 1066.03m
                        },
                        new
                        {
                            Id = 98,
                            Name = "Product 98",
                            PackagingId = 99,
                            Price = 1077.02m
                        },
                        new
                        {
                            Id = 99,
                            Name = "Product 99",
                            PackagingId = 100,
                            Price = 1088.01m
                        },
                        new
                        {
                            Id = 100,
                            Name = "Product 100",
                            PackagingId = 1,
                            Price = 1099.00m
                        });
                });

            modelBuilder.Entity("TakeHomeAssignmentAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwoFactorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwoFactorRecoveryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TakeHomeAssignmentAPI.Models.Packaging_Hierarchy", b =>
                {
                    b.HasOne("TakeHomeAssignmentAPI.Models.Packaging", "ChildPackaging")
                        .WithMany()
                        .HasForeignKey("ChildPackagingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TakeHomeAssignmentAPI.Models.Packaging", "ParentPackaging")
                        .WithMany()
                        .HasForeignKey("ParentPackagingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildPackaging");

                    b.Navigation("ParentPackaging");
                });

            modelBuilder.Entity("TakeHomeAssignmentAPI.Models.Product", b =>
                {
                    b.HasOne("TakeHomeAssignmentAPI.Models.Packaging", "Packaging")
                        .WithMany()
                        .HasForeignKey("PackagingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Packaging");
                });
#pragma warning restore 612, 618
        }
    }
}
